const translations = {
  en: {
    signIn: "Sign In",
    profile: "My Profile",
    myOrders: "My Orders",
    waitingTime: "Waiting Time",
    customerSupport: "Customer Support",
    checkout: "Checkout",
    logout: "Logout",
    heroTitle: "Accessories For Everyone",
    heroDescription: "Discover trendy accessories, keychains, phone accessories, wallets, jewelry and more — all in one place.",
    searchPlaceholder: "Search products",
    new: "New",
    keychains: "Keychains",
    phone: "Phone",
    wallets: "Wallets",
    jewelry: "Jewelry",
    bags: "Bags",
    more: "More",
    newArrivals: "New Arrivals",
    seeAll: "See All",
    shopLatestTitle: "Shop The Latest Collection",
    shopLatestDesc: "Premium quality accessories with affordable prices.",
    shopNow: "Shop Now",
    footerTagline: "Accessories • Quality • Style",
    developer: "Developer and Founder: Rudox",
    creativeLead: "Creative lead and Co-founder: Valrqx",
    stock: "Stock",
    addToCart: "Add to Cart",
    outOfStock: "Out of Stock",
    home: "Homepage",
    waitingTitlePolicy: "Safe Delivery & Waiting Time Policy",
    waitingDesc1: "At Acai Shop, we work alongside Safe Delivery to ensure your packages reach you securely. Below are our regional delivery fees and waiting times. You can comfortably shop using our Cash on Delivery (COD) system with no prepayment required.",
    deliveryPolicyTitle: "Delivery Policy & Timeframe",
    deliveryPolicyDesc: "Orders are typically delivered within 3 days depending on transportation and regional logistics conditions.",
    feeTableTitle: "Delivery Fee & Region Table",
    tableColRegion: "Region / Township Details",
    tableColFee: "Delivery Fee",
    tableColTime: "Waiting Time",
    yangonT1Title: "Yangon (3,500 MMK Townships)",
    yangonT1Sub: "Lanmadaw, Latha, Pabedan, Kyauktada, Pazundaung, Botahtaung, Kyimyindaing, Ahlone, Sanchaung, Insein, Mayangone, Hlaing, Kamayut, South Okkalapa, Thingangyun, Yankin, Dawbon, Thaketa, Tamwe, Bahan, Mingalar Taung Nyunt, Dagon",
    yangonT2Title: "Yangon (4,000 MMK Townships)",
    yangonT2Sub: "Hlaingtharyar, Shwepyithar, North Okkalapa, South Dagon, North Dagon, East Dagon, Dagon Seikkan, Dala, Thanlyin (Up to Kyaik Khauk Pagoda)",
    yangonT3Title: "Yangon (4,500 MMK Townships)",
    yangonT3Sub: "Hmawbi (Up to City Market), Hlegu (Up to City Market)",
    mandalay: "Mandalay",
    naypyitaw: "Naypyitaw",
    sagaing: "Sagaing Region",
    bago: "Bago Region",
    magway: "Magway Region",
    ayeyarwady: "Ayeyarwady Region",
    mon: "Mon State",
    shan: "Shan State",
    myawaddy: "Myawaddy",
    within3Days: "Within 3 Days",
    importantNoteHeading: "Important Note:",
    importantNoteDesc: "Since we use Cash on Delivery (COD), please keep your phone reachable for the delivery rider and ensure your delivery address details are accurate.",
    footerPartner: "Safe Delivery Partner • Quality • Speed • Trust",
    welcomeBack: "Welcome Back",
    signInSubtitle: "Sign in to continue shopping.",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    forgotPassword: "Forgot Password?",
    signInBtnText: "Sign In",
    signingInText: "Signing in...",
    noAccountText: "Don't have an account?",
    registerLink: "Register",
    forgotPasswordTitle: "Forgot Password?",
    forgotPasswordSubtitle: "Enter your registered email address and we'll send you a verification code.",
    enterEmailPlaceholder: "Enter your email",
    sendOtpBtnText: "Send OTP",
    sendingCodeTitle: "Sending verification code...",
    pleaseWaitText: "Please wait a moment.",
    otpSuccessText: "Verification code sent successfully.",
    backToSignIn: "Back to Sign In",
    createAccountTitle: "Create Account",
    createAccountSubtitle: "Enter your email and password to receive a verification code.",
    alreadyHaveAccount: "Already have an account?",
    signInLink: "Sign In",
    continueShopping: "Continue Shopping",
    shoppingCartTitle: "Shopping Cart",
    totalText: "Total",
    proceedCheckout: "Proceed to Checkout",
    cartEmpty: "Your cart is empty",
    remove: "Remove",
    backToCart: "Back to Cart",
    checkoutTitle: "Checkout",
    checkoutSubtitle: "Enter your delivery information.",
    fullName: "Full Name *",
    fullNamePlaceholder: "Enter your full name",
    phoneNumber: "Phone Number *",
    telegramAcc: "Telegram Account / Username *",
    telegramPlaceholder: "@username or Phone Number",
    noTelegram: "I don't have Telegram",
    altSocialLabel: "Where else can we reach you? *",
    altSocialPlaceholder: "e.g., Viber, Instagram, Snapchat, Discord",
    altSocialHelper: "e.g., Viber: Your phone number / Instagram: @username / Snapchat: @username / Discord: @username",
    city: "City *",
    selectCity: "Select City",
    township: "Township *",
    selectTownship: "Select Township",
    road: "Road / Street *",
    roadPlaceholder: "Example: Insein Road",
    building: "Building / Apartment (Optional)",
    buildingPlaceholder: "Apartment, Floor, Room",
    address: "House No. / Landmark *",
    addressPlaceholder: "House No., Landmark",
    paymentMethod: "Payment Method *",
    subtotal: "Subtotal",
    deliFee: "Delivery Fee",
    totalAmount: "Total Amount",
    placeOrder: "Place Order",
     faq: "FAQ",
    customerReviews: "Customer Reviews",
  },
  mm: {
    signIn: "အကောင့်ဝင်ရန်",
    profile: "ကျွန်ုပ်၏ ပရိုဖိုင်",
    myOrders: "ကျွန်ုပ်၏အော်ဒါများ",
    waitingTime: "စောင့်ဆိုင်းချိန်",
    customerSupport: "ဆက်သွယ်ရန်",
    checkout: "ငွေရှင်းရန်",
    logout: "အကောင့်ထွက်ရန်",
    heroTitle: "လူတိုင်းအတွက် အသုံးအဆောင်ပစ္စည်းများ",
    heroDescription: "ခေတ်မီအသုံးအဆောင်ပစ္စည်းများ၊ သော့ချိတ်များ၊ ဖုန်းအသုံးအဆောင်ပစ္စည်းများ၊ ပိုက်ဆံအိတ်များ၊ လက်ဝတ်ရတနာများနှင့် အခြားပစ္စည်းများကို တစ်နေရာတည်းတွင် ရှာဖွေဝယ်ယူနိုင်ပါသည်။",
    searchPlaceholder: "ပစ္စည်းရှာရန်",
    new: "အသစ်များ",
    keychains: "သော့ချိတ်များ",
    phone: "ဖုန်းအသုံးအဆောင်များ",
    wallets: "ပိုက်ဆံအိတ်များ",
    jewelry: "လက်ဝတ်ရတနာများ",
    bags: "အိတ်များ",
    more: "ပိုမိုကြည့်ရန်",
    newArrivals: "အသစ်ရောက်ပစ္စည်းများ",
    seeAll: "အားလုံးကြည့်ရန်",
    shopLatestTitle: "နောက်ဆုံးထွက်ပစ္စည်းများကို ဝယ်ယူလိုက်ပါ",
    shopLatestDesc: "အရည်အသွေးမြင့် အသုံးအဆောင်ပစ္စည်းများကို သင့်တင့်သောဈေးနှုန်းဖြင့် ရရှိနိုင်ပါသည်။",
    shopNow: "ယခုဝယ်ယူရန်",
    footerTagline: "အသုံးအဆောင် • အရည်အသွေး • စတိုင်",
    developer: "တည်ထောင်သူနှင့် ဝဘ်ဆိုက်ဖန်တီးသူ: Rudox",
    creativeLead: "ဖန်တီးမှုဦးဆောင်သူနှင့် ပူးတွဲတည်ထောင်သူ: Valrqx",
    stock: "လက်ကျန်",
    addToCart: "ခြင်းတောင်းထဲထည့်ရန်",
    outOfStock: "ပစ္စည်းပြတ်နေသည်",
    home: "ပင်မစာမျက်နှာ",
    waitingTitlePolicy: "Safe Delivery နှင့် စောင့်ဆိုင်းချိန် မူဝါဒ",
    waitingDesc1: "Acai Shop မှ ပစ္စည်းများကို Safe Delivery နှင့် ချိတ်ဆက်၍ လုံခြုံစိတ်ချစွာ ပို့ဆောင်ပေးနေပါသည်။ အောက်ပါဇယားတွင် မြို့နယ်အလိုက် ပို့ဆောင်ခနှင့် စောင့်ဆိုင်းရမည့်ရက်များကို ကြည့်ရှုနိုင်ပါသည်။ ငွေကြိုတင်ပေးစရာမလိုဘဲ အိမ်ရောက်ငွေချေစနစ် (Cash on Delivery - COD) ဖြင့် အလွယ်တကူ ဝယ်ယူနိုင်ပါသည်။",
    deliveryPolicyTitle: "ပို့ဆောင်ရေး မူဝါဒနှင့် အချိန်ဇယား",
    deliveryPolicyDesc: "လမ်းပန်းဆက်သွယ်ရေးနှင့် ဒေသအခြေအနေများအပေါ်မူတည်၍ အော်ဒါများကို ပုံမှန်အားဖြင့် ရက်ပေါင်း ၃ ရက် အတွင်း ပို့ဆောင်ပေးပါသည်။",
    feeTableTitle: "ပို့ဆောင်ခနှင့် မြို့နယ်ဇယား",
    tableColRegion: "မြို့နယ် / ဒေသ အသေးစိတ်",
    tableColFee: "ပို့ဆောင်ခ",
    tableColTime: "စောင့်ဆိုင်းချိန်",
    yangonT1Title: "ရန်ကုန် (၃,၅၀၀ ကျပ်တန် မြို့နယ်များ)",
    yangonT1Sub: "လသာ၊ လမ်းမတော်၊ ပန်းဘဲတန်း၊ ကျောက်တံတား၊ ပုဇွန်တောင်၊ ဗိုလ်တထောင်၊ ကြည့်မြင်တိုင်၊ အလုံ၊ စမ်းချောင်း၊ အင်းစိန်၊ မရမ်းကုန်း၊ လှိုင်၊ ကမာရွတ်၊ တောင်ဥက္ကလာပ၊ သင်္ဃန်းကျွန်း၊ ရန်ကင်း၊ ဒေါပုံ၊ သာကေတ၊ တာမွေ၊ ဗဟန်း၊ မင်္ဂလာတောင်ညွန့်၊ ဒဂုံ",
    yangonT2Title: "ရန်ကုန် (၄,၀၀၀ ကျပ်တန် မြို့နယ်များ)",
    yangonT2Sub: "လှိုင်သာယာ၊ ရွှေပြည်သာ၊ မြောက်ဥက္ကလာပ၊ တောင်ဒဂုံ၊ မြောက်ဒဂုံ၊ အရှေ့ဒဂုံ၊ ဒဂုံဆိပ်ကမ်း၊ ဒလ၊ သန်လျင် (ကျိုက်ခေါက်ဘုရားအထိ)",
    yangonT3Title: "ရန်ကုန် (၄,၅၀၀ ကျပ်တန် မြို့နယ်များ)",
    yangonT3Sub: "မှော်ဘီ (မြို့မဈေးထိ)၊ လှည်းကူး (လှည်းကူးဈေးထိ)",
    mandalay: "မန္တလေး",
    naypyitaw: "နေပြည်တော်",
    sagaing: "စစ်ကိုင်းတိုင်းဒေသကြီး",
    bago: "ပဲခူးတိုင်းဒေသကြီး",
    magway: "မကွေးတိုင်းဒေသကြီး",
    ayeyarwady: "ဧရာဝတီတိုင်းဒေသကြီး",
    mon: "မွန်ပြည်နယ်",
    shan: "ရှမ်းပြည်နယ်",
    myawaddy: "မြဝတီ",
    within3Days: "၃ ရက်အတွင်း",
    importantNoteHeading: "အထူးသတိပြုရန်:",
    importantNoteDesc: "အိမ်ရောက်ငွေချေစနစ် (COD) ကို အသုံးပြုထားသောကြောင့် ပို့ဆောင်မည့် Delivery ဝန်ထမ်း ဆက်သွယ်လာပါက ဖုန်းကို လက်ခံဖြေဆိုနိုင်ရန်နှင့် လိပ်စာ အချက်အလက်များ တိကျမှန်ကန်စေရန် ကြိုတင်မေတ္တာရပ်ခံအပ်ပါသည်။",
    welcomeBack: "ကြိုဆိုပါတယ်",
    signInSubtitle: "ဆက်လက်ဝယ်ယူရန် အကောင့်ဝင်ပါ။",
    emailPlaceholder: "အီးမေးလ်",
    passwordPlaceholder: "စကားဝှက်",
    forgotPassword: "စကားဝှက်မေ့နေပါသလား?",
    signInBtnText: "အကောင့်ဝင်ရန်",
    signingInText: "အကောင့်ဝင်နေပါသည်...",
    noAccountText: "အကောင့်မရှိသေးဘူးလား?",
    registerLink: "အကောင့်အသစ်ဖွင့်ရန်",
    forgotPasswordTitle: "စကားဝှက်မေ့နေပါသလား?",
    forgotPasswordSubtitle: "သင့်အကောင့်ဖွင့်ထားသော အီးမေးလ်လိပ်စာကို ထည့်သွင်းပါ၊ ကျွန်ုပ်တို့ အတည်ပြုကုဒ် (OTP) ပို့ပေးပါမည်။",
    enterEmailPlaceholder: "သင့်အီးမေးလ်ကို ထည့်ပါ",
    sendOtpBtnText: "OTP ပို့ရန်",
    sendingCodeTitle: "အတည်ပြုကုဒ် ပို့နေပါသည်...",
    pleaseWaitText: "ခဏလောက် စောင့်ပေးပါ။",
    otpSuccessText: "အတည်ပြုကုဒ် အောင်မြင်စွာ ပို့ပြီးပါပြီ။",
    backToSignIn: "အကောင့်ဝင်ရန်သို့ ပြန်သွားရန်",
    createAccountTitle: "အကောင့်အသစ်ဖွင့်ရန်",
    createAccountSubtitle: "အတည်ပြုကုဒ် လက်ခံရရှိရန် သင့်အီးမေးလ်နှင့် စကားဝှက်ကို ထည့်ပါ။",
    alreadyHaveAccount: "အကောင့်ရှိပြီးသားလား?",
    signInLink: "အကောင့်ဝင်ရန်",
    continueShopping: "ပစ္စည်းဆက်ဝယ်ရန်",
    shoppingCartTitle: "ခြင်းတောင်း",
    totalText: "စုစုပေါင်း",
    proceedCheckout: "ငွေချေရန် ဆက်သွားမည်",
    cartEmpty: "သင်၏ ခြင်းတောင်းထဲတွင် ပစ္စည်းမရှိပါ",
    remove: "ဖယ်ရှားရန်",
    backToCart: "ခြင်းတောင်းသို့ ပြန်ရန်",
    checkoutTitle: "ငွေချေရန်",
    checkoutSubtitle: "ပို့ဆောင်ရမည့် လိပ်စာအချက်အလက်များကို ဖြည့်သွင်းပါ။",
    fullName: "အမည်အပြည့်အစုံ *",
    fullNamePlaceholder: "သင့်အမည်ကို ထည့်ပါ",
    phoneNumber: "ဖုန်းနံပါတ် *",
    telegramAcc: "Telegram အကောင့် / Username *",
    telegramPlaceholder: "@username သို့မဟုတ် ဖုန်းနံပါတ်",
    noTelegram: "Telegram မရှိပါ",
    altSocialLabel: "အခြားဆက်သွယ်ရန် လူမှုကွန်ရက် *",
    altSocialPlaceholder: "ဥပမာ - Viber, Instagram, Snapchat, Discord",
    altSocialHelper: "ဥပမာ - Viber: ဖုန်းနံပါတ် / Instagram: @username / Snapchat: @username / Discord: @username",
    city: "မြို့ / မြို့ကြီး *",
    selectCity: "မြို့ကို ရွေးပါ",
    township: "မြို့နယ် *",
    selectTownship: "မြို့နယ်ကို ရွေးပါ",
    road: "လမ်းနာမည် *",
    roadPlaceholder: "ဥပမာ - အင်းစိန်လမ်း",
    building: "တိုက်ခန်း / အထပ် (ဖြည့်ရန်မလိုပါ)",
    buildingPlaceholder: "တိုက်ခန်း၊ အထပ်၊ အခန်း",
    address: "အိမ်နံပါတ် / အနီးအနား အမှတ်အသား *",
    addressPlaceholder: "အိမ်နံပါတ်၊ အမှတ်အသား",
    paymentMethod: "ငွေပေးချေမည့် နည်းလမ်း *",
    subtotal: "ပစ္စည်းတန်ဖိုးစုစုပေါင်း",
    deliFee: "ပို့ခ",
    totalAmount: "စုစုပေါင်း ကျသင့်ငွေ",
    placeOrder: "အော်ဒါတင်မည်",
      faq: "မေးလေ့ရှိသောမေးခွန်းများ",
    customerReviews: "ဝယ်ယူသူများ၏ သုံးသပ်ချက်များ",
  }
};
function changeLanguage(lang) {
  localStorage.setItem("language", lang);

  document.querySelectorAll("[data-lang]").forEach(el => {
    const key = el.dataset.lang;
    if (translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });

  document.querySelectorAll("[data-lang-placeholder]").forEach(el => {
    const key = el.dataset.langPlaceholder;
    if (translations[lang] && translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  const city = document.getElementById("city");
  if (city && typeof updateTownships === "function") {
    updateTownships();
  }

  if (typeof togglePaymentInfo === "function") {
    togglePaymentInfo();
  }

  if (typeof loadProducts === "function") {
    loadProducts();
  }
}